version: '3.8'

services:
  app1:
    build: ./app
    environment:
      - PORT=3000
    expose:
      - "3000"
      
  app2:
    build: ./app
    environment:
      - PORT=3000
    expose:
      - "3001"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2